name: legacy_calendar
description: "A customizable and themeable calendar widget for Flutter that provides a classic calendar view."
version: 0.0.8
license: MIT
homepage: https://github.com/barneysspeedshop/legacy_calendar
repository: https://github.com/barneysspeedshop/legacy_calendar
issue_tracker: https://github.com/barneysspeedshop/legacy_calendar/issues

topics:
  - calendar
  - schedule
  - events

screenshots:
  - description: 'Legacy Calendar month view with events.'
    path: assets/example.png

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
