name: legacy_calendar
description: "A customizable and themeable calendar widget for Flutter that provides a classic calendar view."
version: 1.0.0
homepage: # TODO: Add your package's homepage URL, e.g., a GitHub repository.

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

screenshots:
  - assets/screenshot.png